providers/redfish: fixes test case failure
Tests should not call into the Gofish, although since we're checking the session
before attempting any redfish call, this would result in a panic. This adds
a workaround to skip the GetSession() while running tests.

A fix for the panic in Gofish has be proposed https://github.com/stmcginnis/gofish/pull/214

--- FAIL: Test_FirmwareInstall (0.00s)
    --- FAIL: Test_FirmwareInstall/applyAt_parameter_invalid (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x12e017c]

goroutine 38 [running]:
testing.tRunner.func1.2({0x1334680, 0x16164b0})
        /Users/jrebello/sdk/go1.19/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
        /Users/jrebello/sdk/go1.19/src/testing/testing.go:1399 +0x39f
panic({0x1334680, 0x16164b0})
        /Users/jrebello/sdk/go1.19/src/runtime/panic.go:884 +0x212
github.com/stmcginnis/gofish.(*APIClient).GetSession(0xc0002944a0?)
        /Users/jrebello/go/pkg/mod/github.com/stmcginnis/gofish@v0.13.0/client.go:249 +0x1c
github.com/bmc-toolbox/bmclib/v2/providers/redfish.(*Conn).sessionActive(0x31?, {0xc000294508?, 0x105693e?})
        /Users/jrebello/go/src/github.com/bmc-toolbox/bmclib.v2/providers/redfish/redfish.go:161 +0x34
github.com/bmc-toolbox/bmclib/v2/providers/redfish.(*Conn).FirmwareInstall(0xc0001fe300, {0x142bf10, 0xc00018e010}, {0x138bb1f, 0x4}, {0x138ee6e, 0xe}, 0x0, {0x0, 0x0})
        /Users/jrebello/go/src/github.com/bmc-toolbox/bmclib.v2/providers/redfish/firmware.go:35 +0x74
github.com/bmc-toolbox/bmclib/v2/providers/redfish.Test_FirmwareInstall.func1(0xc0000829c0?)
        /Users/jrebello/go/src/github.com/bmc-toolbox/bmclib.v2/providers/redfish/firmware_test.go:117 +0x85
testing.tRunner(0xc000082b60, 0xc00008e450)
        /Users/jrebello/sdk/go1.19/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
        /Users/jrebello/sdk/go1.19/src/testing/testing.go:1493 +0x35f
FAIL    github.com/bmc-toolbox/bmclib/v2/providers/redfish      0.019s
FAIL
make: *** [test] Error 1